name: Trigger auto deployment for container-app-3qagfxrtfnjae

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-3qagfxrtfnjae-AutoDeployTrigger-56e2f5e3-ab0c-4ae9-be82-39ccfe09929f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3QAGFXRTFNJAE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3QAGFXRTFNJAE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3QAGFXRTFNJAE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry3qagfxrtfnjae.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP3QAGFXRTFNJAE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3QAGFXRTFNJAE_REGISTRY_PASSWORD }}
          containerAppName: container-app-3qagfxrtfnjae
          resourceGroup: localragexample94f3
          imageToBuild: containerregistry3qagfxrtfnjae.azurecr.io/container-app-3qagfxrtfnjae:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


